############################
## CHANGE THESE
############################

baseURL: "https://massylii.github.io/"
languageCode: "en-us"
title: "MASSYLII"
theme: "qubt"


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true


