############################
## Author
############################

author:
  name: "MASSYLII"
  image: pfp2.png
  greeting: "Wellcome to my blog!"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/massylii
  # - gitlab: 
  #- facebook: https://github.com/chrede88/qubt
  - x-twitter: https://x.com/massylii
  # - mastodon:
  #- linkedin: https://github.com/chrede88/qubt
  - instagram: https://www.instagram.com/rexivba/
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  #- email:  
  - website: https://massylii.github.io/
  # - link: 
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "Qubt Theme"
description: "Demo site build with Qubt & Hugo"
images:
  - thumbnail.png