name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Add your build steps here if needed

      - name: Deploy
        run: |
          cd public
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git init
          git remote add origin https://github.com/massylii/massylii.github.io.git
          git checkout -b main
          git add .
          git commit -m "Deploy site"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}