name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build the Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_DEPLOY }}  # Use the Personal Access Token
        run: |
          cd public
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://github.com/massylii/massylii.github.io.git
          git checkout -b main
          git add .
          git commit -m "Deploy site"
          git push --force origin main
